# Generated by Django 6.0.7 on 2026-07-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='America/Bogota', max_length=50),
        ),
    ]
